[data]
vocab_size = 14900
seq_length = 64
test_split = 0.2
data_path = "dataset/"
data_tensors_path = "data_tensors/"

[model]
embedding_dim = 128
num_blocks = 2
num_heads_in_block = 2
dropout = 0.4

[train]
num_train_iter = 25000
num_test_iter = 5000
test_interval = 1000
batch_size = 32
learning_rate = 0.0001
checkpoint_path = "auto"
wandb_logging_enabled = false
wandb_project_name = "Poem Maker Transformer"
compile_model = true
resume_training = false
resume_training_checkpoint_path = ""

[deploy]
host = "0.0.0.0"
port = 8080
