[data]
vocab_size = 5589
seq_length = 10
test_split = 0.2
data_path = "dataset/"
data_tensors_path = "data_tensors/"

[model]
embedding_dim = 256
num_blocks = 5
num_heads_in_block = 3

[train]
num_epochs = 10
batch_size = 32
learning_rate = 0.0003
checkpoint_path = "auto"
wandb_logging_enabled = false
wandb_project_name = "Poem Maker Transformer"

[deploy]
host = "0.0.0.0"
port = 8080
